version: '3'
services:
  api:
    container_name: api
    build:
      context: .
      args:
        - WITH_XDEBUG=true
    env_file: .env
    ports:
      - "8001:8001"
    volumes:
      - .:/var/www/web
    links:
      - redis
      - db
  redis:
    image: "redis:alpine"
    ports:
      - "63791:6379"
  echo-server:
    image: "lagun4ik/laravel-echo-server"
    ports:
      - "60061:6001"
    volumes:
      - .:/app
    links:
      - redis
      - api
  db:
    image: "mariadb:10.2"
    environment:
      MYSQL_ROOT_PASSWORD: "1"
      MYSQL_DATABASE: "web"
    ports:
      - "33061:3306"

